baseURL: "https://Alex-Hackett.github.io" 
title: Alexander J. Hackett
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: 
          weight: 6

params:
    description: "My name is Alexander Hackett, I'm a postdoctoral research scientist, an astronomer, a stellar physicist, a research software developer, and a passionate scientist, science communicator, and public speaker."
    author: Alexander J. Hackett
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Alexander J. Hackett
          subtitle: "I am currently a postdoctoral researcher at the Institute of Physics of the Czech Academy of Sciences in Prague, working on developing stellar evolution models as tests of fundamental physics, specifically, using such models to investigate the field density of primordial black holes and time evolution of fundamental constants. We are also making use of asteroseismology codes, primarily GYRE, in order to attempt to split the degeneracy we observe between the effects of code-specific variables, and that of actual physical effects induced by the presence of a primordial black hole.
Prior to this position, I completed my Ph.D. at the Institute of Astronomy of the University of Cambridge, under the supervision of Chris Tout and Anna Żytkow, with stellar evolution and modelling, specifically of (exotic) compact objects and hybrid stars being the main focus of my research and thesis."
          imageUrl: "picture.jpeg"
          #imageWidth: 160
          #imageHeight: 160
          buttons:
            - name: Papers
              url: 
            - name: Courses
              url: 
            - name: Data
              url: 
            - name: Books
              url: 
            - name: Tags
              url: 
            - name: Archive
              url: 
            - name: Blog
              url: 

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ahackett@tcd.ie
        - name: Zoom
          url: https://cam-ac-uk.zoom.us/j/5783087810?pwd=MHQ3aUE0MEJiTDA3eUVCT1k1Z2luUT09
        - name: Location
          url: 
        - name: Office Hours
          url: 
        - name: Google Scholar
          url: 
        - name: GitHub
          url: https://github.com/Alex-Hackett
        - name: Substack
          url: 
        - name: YouTube
          url: 
        - name: Twitter
          url: https://x.com/CantEvenHackett

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alexander J. Hackett"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
